In [1]:
import numpy as np
import cupy as cp

ModuleNotFoundError: No module named 'cupy'

In [ ]:
def unbroadcast(grad, target_shape):
    ndims_added = grad.ndim - len(target_shape)
    xp = np
    if ndims_added > 0:
        grad = xp.sum(grad, axis = tuple(range(ndims_added)))
    
    for i, dim_size in enumerate(target_shape):
        if dim_size == 1 and grad.shape[i] > 1:
            grad = xp.sum(grad, axis = i, keepdims=True)
            
    return grad

In [2]:
grad = np.array([
    [
        [1,  2,  3,  4],
        [5,  6,  7,  8],
        [9, 10, 11, 12]
    ],
    [
        [13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]
    ]
])

target_shape = (4,)

In [15]:
a = unbroadcast(grad = grad, target_shape=target_shape)

a

array([66, 72, 78, 84])

In [1]:
from torch import Tensor

In [5]:
a = Tensor([1,2,3,4], requires_grad=True, device='cpu')
b = Tensor([1,1,1,1], requires_grad=True, device='cpu')

c = a + b

In [6]:
d = a@b
d.data

array(10., dtype=float32)

In [7]:
e = -a
e.data

array([-1., -2., -3., -4.], dtype=float32)

In [13]:
(e.backward(grad = [1,2,3,4]))

TypeError: bad operand type for unary -: 'list'

In [9]:
e

Tensor: [-1. -2. -3. -4.], requires_grad: True

In [24]:
x = Tensor([1,2,3,4], requires_grad=True)
y = x * x
z = x + y
z.backward()
print(x.grad, y.grad, z.grad)

[3. 5. 7. 9.] [1. 1. 1. 1.] [1. 1. 1. 1.]


In [3]:
x = Tensor([1,2,3,4], requires_grad=True)
y = x * x
z = x + y
z.backward([1,1,1,1])
print(x.grad, y.grad, z.grad)

[3. 5. 7. 9.] [1. 1. 1. 1.] [1. 1. 1. 1.]


In [26]:
x = Tensor(3.0, requires_grad=True)
y = x * x
z = x + y
z.backward()
print(x.grad, y.grad, z.grad)

7.0 1.0 1.0


In [27]:
x = Tensor(3.0, requires_grad=True)
y = x * x
z = x + y
z.backward(2.0)
print(x.grad, y.grad, z.grad)

AttributeError: 'float' object has no attribute 'ndim'

In [28]:
x = Tensor(3.0, requires_grad=True)
y = x * x
y.backward(2.0)
print(x.grad, y.grad)

12.0 2.0


In [29]:
x = Tensor([1,2,3,4], requires_grad=True)
y = x * x
z = x + y
z.backward(np.ones(4))
print(x.grad, y.grad, z.grad, x.grad.dtype)

[3. 5. 7. 9.] [1. 1. 1. 1.] [1. 1. 1. 1.] float64


In [30]:
x = Tensor([1,2,3,4], requires_grad=True)
y = x * x
z = x + y
z.backward(np.ones((2,4)))
print(x.grad, y.grad, z.grad)

[ 6. 10. 14. 18.] [2. 2. 2. 2.] [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [31]:
x = Tensor([1,2,3,4], requires_grad=True)
y = x * x
z = x + y
z.backward(Tensor([1,1,1,1]))
print(x.grad, y.grad, z.grad)

TypeError: float() argument must be a string or a real number, not 'Tensor'

In [32]:
x = Tensor([1,2,3,4], requires_grad=True)
y = x * x
z = x + y
z.backward([1,0,0,0])
print(x.grad, y.grad, z.grad)

AttributeError: 'list' object has no attribute 'ndim'

In [33]:
x = Tensor([1,2,3,4], requires_grad=False)
y = x * x
z = x + y
z.backward([1,1,1,1])
print(x.grad, y.grad, z.grad)

RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

In [6]:
x = Tensor(2, requires_grad=True)
y = x * x
z = x + y                   # z has 4 numbers: [2, 6, 12, 20]

z.backward()                # empty brackets
print("Ex1:", x.grad, y.grad, z.grad)

Ex1: 5.0 1.0 1.0


In [1]:
from torch import Tensor

In [8]:
x = Tensor([1,2,3], requires_grad=True)
y = x*x
y.backward([1,1,1])

In [9]:
x.grad

array([2., 4., 6.], dtype=float32)

In [17]:
x.data -= 0.1*x.grad
x

Tensor: [8.000001  7.0000005 6.       ], requires_grad: True

In [11]:
x.data = [9,9,9]

In [12]:
x

Tensor: [9. 9. 9.], requires_grad: True